version: 3.0
- command:
   name: setup
   execute:
      - wish scripts/setup.tcl
   description: Open configuration UI
   flags:
      - unixpath
- command:
   name: autosetup
   execute:
      - scripts/setup.tcl --nogui
   description: Auto configure build variables
   flags:
      - unixonly
- command:
   name: autosetup
   execute:
      - wish scripts\setup.tcl --nogui
   description: Auto configure build variables
   flags:
      - windowsonly
- command:
   name: install
   execute:
      - gprinstall -f -P tashy.gpr --create-missing-dirs -XLIBRARY_TYPE=static --build-var=LIBRARY_TYPE --build-name=static
      - gprinstall -f -P tashy.gpr --create-missing-dirs -XLIBRARY_TYPE=relocatable --build-var=LIBRARY_TYPE --build-name=relocatable
   description: Install the library for use with GNAT
   flags:
      - unixonly
- command:
   name: build
   execute:
      - gprbuild -P tashy.gpr -XLIBRARY_TYPE=static
      - gprbuild -P tashy.gpr -XLIBRARY_TYPE=relocatable
   description: Build the library
   flags:
      - unixonly
- command:
   name: install
   execute:
      - gprinstall -f -P tashy.gpr --create-missing-dirs -XLIBRARY_TYPE=static --build-var=LIBRARY_TYPE --build-name=static
   description: Install the library for use with GNAT
   flags:
      - windowsonly
- command:
   name: build
   execute:
      - gprbuild -P tashy.gpr -XLIBRARY_TYPE=static
   description: Build the library
   flags:
      - windowsonly
- command:
   name: clean
   execute:
      - tclsh scripts/clean.tcl
   description: Clear compilation of the library.
   flags:
      - unixpath
- command:
   name: builddemos
   execute:
      - cd demos
      - gprbuild -P tash_demos.gpr
   description: Build the library demos
- command:
   name: cleardemos
   execute:
      - cd demos
      - gprclean -P tash_demos.gpr
   description: Clear the library demos
- command:
   name: docs
   execute:
      - tclsh scripts/generatedocs.tcl
   description: Generate code documentation (default dark theme)
   flags:
      - unixpath
- command:
   name: uninstall
   execute:
      - gprinstall --uninstall -P tashy.gpr
   description: Uninstall the library for use with GNAT
- command:
   name: docslight
   execute:
      - tclsh scripts/generatedocs.tcl scripts/robodocada.rc docs scripts/robodoclight.css
   description: Generate code documentation (with light theme)
   flags:
      - unixpath
- command:
   name: pretty
   execute:
      - gnatpp -P tashy.gpr
   description: Pretty print Tashy source code
- command:
   name: push
   execute:
      - fossil push
      - fossil git export
   description: Update remove Fossil repository and its Git mirror
